/* tslint:disable */
/* eslint-disable */
/**
 * SP2407 Nearby Stations API
 * 周辺のステーションの座標を取得し、各ステーションに対してRed/Greenチームに投票し、写真をアップロードするためのAPIです。
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: support@sp2407.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

