from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.get_teams_info200_response_green import GetTeamsInfo200ResponseGreen
from openapi_server.models.get_teams_info200_response_red import GetTeamsInfo200ResponseRed
from openapi_server import util

from openapi_server.models.get_teams_info200_response_green import GetTeamsInfo200ResponseGreen  # noqa: E501
from openapi_server.models.get_teams_info200_response_red import GetTeamsInfo200ResponseRed  # noqa: E501

class GetTeamsInfo200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, red=None, green=None):  # noqa: E501
        """GetTeamsInfo200Response - a model defined in OpenAPI

        :param red: The red of this GetTeamsInfo200Response.  # noqa: E501
        :type red: GetTeamsInfo200ResponseRed
        :param green: The green of this GetTeamsInfo200Response.  # noqa: E501
        :type green: GetTeamsInfo200ResponseGreen
        """
        self.openapi_types = {
            'red': GetTeamsInfo200ResponseRed,
            'green': GetTeamsInfo200ResponseGreen
        }

        self.attribute_map = {
            'red': 'Red',
            'green': 'Green'
        }

        self._red = red
        self._green = green

    @classmethod
    def from_dict(cls, dikt) -> 'GetTeamsInfo200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getTeamsInfo_200_response of this GetTeamsInfo200Response.  # noqa: E501
        :rtype: GetTeamsInfo200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def red(self) -> GetTeamsInfo200ResponseRed:
        """Gets the red of this GetTeamsInfo200Response.


        :return: The red of this GetTeamsInfo200Response.
        :rtype: GetTeamsInfo200ResponseRed
        """
        return self._red

    @red.setter
    def red(self, red: GetTeamsInfo200ResponseRed):
        """Sets the red of this GetTeamsInfo200Response.


        :param red: The red of this GetTeamsInfo200Response.
        :type red: GetTeamsInfo200ResponseRed
        """

        self._red = red

    @property
    def green(self) -> GetTeamsInfo200ResponseGreen:
        """Gets the green of this GetTeamsInfo200Response.


        :return: The green of this GetTeamsInfo200Response.
        :rtype: GetTeamsInfo200ResponseGreen
        """
        return self._green

    @green.setter
    def green(self, green: GetTeamsInfo200ResponseGreen):
        """Sets the green of this GetTeamsInfo200Response.


        :param green: The green of this GetTeamsInfo200Response.
        :type green: GetTeamsInfo200ResponseGreen
        """

        self._green = green
