from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NearbyStationsResponseInnerCoordinates(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, latitude=None, longitude=None):  # noqa: E501
        """NearbyStationsResponseInnerCoordinates - a model defined in OpenAPI

        :param latitude: The latitude of this NearbyStationsResponseInnerCoordinates.  # noqa: E501
        :type latitude: float
        :param longitude: The longitude of this NearbyStationsResponseInnerCoordinates.  # noqa: E501
        :type longitude: float
        """
        self.openapi_types = {
            'latitude': float,
            'longitude': float
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude'
        }

        self._latitude = latitude
        self._longitude = longitude

    @classmethod
    def from_dict(cls, dikt) -> 'NearbyStationsResponseInnerCoordinates':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NearbyStationsResponse_inner_coordinates of this NearbyStationsResponseInnerCoordinates.  # noqa: E501
        :rtype: NearbyStationsResponseInnerCoordinates
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self) -> float:
        """Gets the latitude of this NearbyStationsResponseInnerCoordinates.


        :return: The latitude of this NearbyStationsResponseInnerCoordinates.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: float):
        """Sets the latitude of this NearbyStationsResponseInnerCoordinates.


        :param latitude: The latitude of this NearbyStationsResponseInnerCoordinates.
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longitude(self) -> float:
        """Gets the longitude of this NearbyStationsResponseInnerCoordinates.


        :return: The longitude of this NearbyStationsResponseInnerCoordinates.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: float):
        """Sets the longitude of this NearbyStationsResponseInnerCoordinates.


        :param longitude: The longitude of this NearbyStationsResponseInnerCoordinates.
        :type longitude: float
        """

        self._longitude = longitude
