from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.stations_nearby_get200_response_inner_coordinates import StationsNearbyGet200ResponseInnerCoordinates
from openapi_server.models.stations_nearby_get200_response_inner_total_votes import StationsNearbyGet200ResponseInnerTotalVotes
from openapi_server import util

from openapi_server.models.stations_nearby_get200_response_inner_coordinates import StationsNearbyGet200ResponseInnerCoordinates  # noqa: E501
from openapi_server.models.stations_nearby_get200_response_inner_total_votes import StationsNearbyGet200ResponseInnerTotalVotes  # noqa: E501

class StationsNearbyGet200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, station_id=None, station_name=None, coordinates=None, total_votes=None):  # noqa: E501
        """StationsNearbyGet200ResponseInner - a model defined in OpenAPI

        :param station_id: The station_id of this StationsNearbyGet200ResponseInner.  # noqa: E501
        :type station_id: str
        :param station_name: The station_name of this StationsNearbyGet200ResponseInner.  # noqa: E501
        :type station_name: str
        :param coordinates: The coordinates of this StationsNearbyGet200ResponseInner.  # noqa: E501
        :type coordinates: StationsNearbyGet200ResponseInnerCoordinates
        :param total_votes: The total_votes of this StationsNearbyGet200ResponseInner.  # noqa: E501
        :type total_votes: StationsNearbyGet200ResponseInnerTotalVotes
        """
        self.openapi_types = {
            'station_id': str,
            'station_name': str,
            'coordinates': StationsNearbyGet200ResponseInnerCoordinates,
            'total_votes': StationsNearbyGet200ResponseInnerTotalVotes
        }

        self.attribute_map = {
            'station_id': 'stationId',
            'station_name': 'stationName',
            'coordinates': 'coordinates',
            'total_votes': 'totalVotes'
        }

        self._station_id = station_id
        self._station_name = station_name
        self._coordinates = coordinates
        self._total_votes = total_votes

    @classmethod
    def from_dict(cls, dikt) -> 'StationsNearbyGet200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _stations_nearby_get_200_response_inner of this StationsNearbyGet200ResponseInner.  # noqa: E501
        :rtype: StationsNearbyGet200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def station_id(self) -> str:
        """Gets the station_id of this StationsNearbyGet200ResponseInner.

        ステーションのID。  # noqa: E501

        :return: The station_id of this StationsNearbyGet200ResponseInner.
        :rtype: str
        """
        return self._station_id

    @station_id.setter
    def station_id(self, station_id: str):
        """Sets the station_id of this StationsNearbyGet200ResponseInner.

        ステーションのID。  # noqa: E501

        :param station_id: The station_id of this StationsNearbyGet200ResponseInner.
        :type station_id: str
        """

        self._station_id = station_id

    @property
    def station_name(self) -> str:
        """Gets the station_name of this StationsNearbyGet200ResponseInner.

        ステーションの名前。  # noqa: E501

        :return: The station_name of this StationsNearbyGet200ResponseInner.
        :rtype: str
        """
        return self._station_name

    @station_name.setter
    def station_name(self, station_name: str):
        """Sets the station_name of this StationsNearbyGet200ResponseInner.

        ステーションの名前。  # noqa: E501

        :param station_name: The station_name of this StationsNearbyGet200ResponseInner.
        :type station_name: str
        """

        self._station_name = station_name

    @property
    def coordinates(self) -> StationsNearbyGet200ResponseInnerCoordinates:
        """Gets the coordinates of this StationsNearbyGet200ResponseInner.


        :return: The coordinates of this StationsNearbyGet200ResponseInner.
        :rtype: StationsNearbyGet200ResponseInnerCoordinates
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates: StationsNearbyGet200ResponseInnerCoordinates):
        """Sets the coordinates of this StationsNearbyGet200ResponseInner.


        :param coordinates: The coordinates of this StationsNearbyGet200ResponseInner.
        :type coordinates: StationsNearbyGet200ResponseInnerCoordinates
        """

        self._coordinates = coordinates

    @property
    def total_votes(self) -> StationsNearbyGet200ResponseInnerTotalVotes:
        """Gets the total_votes of this StationsNearbyGet200ResponseInner.


        :return: The total_votes of this StationsNearbyGet200ResponseInner.
        :rtype: StationsNearbyGet200ResponseInnerTotalVotes
        """
        return self._total_votes

    @total_votes.setter
    def total_votes(self, total_votes: StationsNearbyGet200ResponseInnerTotalVotes):
        """Sets the total_votes of this StationsNearbyGet200ResponseInner.


        :param total_votes: The total_votes of this StationsNearbyGet200ResponseInner.
        :type total_votes: StationsNearbyGet200ResponseInnerTotalVotes
        """

        self._total_votes = total_votes
