from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.stations_nearby_get200_response_inner_total_votes import StationsNearbyGet200ResponseInnerTotalVotes
from openapi_server import util

from openapi_server.models.stations_nearby_get200_response_inner_total_votes import StationsNearbyGet200ResponseInnerTotalVotes  # noqa: E501

class StationsStationIdVotePost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, station_id=None, team=None, total_votes=None):  # noqa: E501
        """StationsStationIdVotePost200Response - a model defined in OpenAPI

        :param station_id: The station_id of this StationsStationIdVotePost200Response.  # noqa: E501
        :type station_id: str
        :param team: The team of this StationsStationIdVotePost200Response.  # noqa: E501
        :type team: str
        :param total_votes: The total_votes of this StationsStationIdVotePost200Response.  # noqa: E501
        :type total_votes: StationsNearbyGet200ResponseInnerTotalVotes
        """
        self.openapi_types = {
            'station_id': str,
            'team': str,
            'total_votes': StationsNearbyGet200ResponseInnerTotalVotes
        }

        self.attribute_map = {
            'station_id': 'stationId',
            'team': 'team',
            'total_votes': 'totalVotes'
        }

        self._station_id = station_id
        self._team = team
        self._total_votes = total_votes

    @classmethod
    def from_dict(cls, dikt) -> 'StationsStationIdVotePost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _stations__stationId__vote_post_200_response of this StationsStationIdVotePost200Response.  # noqa: E501
        :rtype: StationsStationIdVotePost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def station_id(self) -> str:
        """Gets the station_id of this StationsStationIdVotePost200Response.

        投票したステーションのID。  # noqa: E501

        :return: The station_id of this StationsStationIdVotePost200Response.
        :rtype: str
        """
        return self._station_id

    @station_id.setter
    def station_id(self, station_id: str):
        """Sets the station_id of this StationsStationIdVotePost200Response.

        投票したステーションのID。  # noqa: E501

        :param station_id: The station_id of this StationsStationIdVotePost200Response.
        :type station_id: str
        """

        self._station_id = station_id

    @property
    def team(self) -> str:
        """Gets the team of this StationsStationIdVotePost200Response.

        投票されたチームの名前。  # noqa: E501

        :return: The team of this StationsStationIdVotePost200Response.
        :rtype: str
        """
        return self._team

    @team.setter
    def team(self, team: str):
        """Sets the team of this StationsStationIdVotePost200Response.

        投票されたチームの名前。  # noqa: E501

        :param team: The team of this StationsStationIdVotePost200Response.
        :type team: str
        """
        allowed_values = ["Red", "Green"]  # noqa: E501
        if team not in allowed_values:
            raise ValueError(
                "Invalid value for `team` ({0}), must be one of {1}"
                .format(team, allowed_values)
            )

        self._team = team

    @property
    def total_votes(self) -> StationsNearbyGet200ResponseInnerTotalVotes:
        """Gets the total_votes of this StationsStationIdVotePost200Response.


        :return: The total_votes of this StationsStationIdVotePost200Response.
        :rtype: StationsNearbyGet200ResponseInnerTotalVotes
        """
        return self._total_votes

    @total_votes.setter
    def total_votes(self, total_votes: StationsNearbyGet200ResponseInnerTotalVotes):
        """Sets the total_votes of this StationsStationIdVotePost200Response.


        :param total_votes: The total_votes of this StationsStationIdVotePost200Response.
        :type total_votes: StationsNearbyGet200ResponseInnerTotalVotes
        """

        self._total_votes = total_votes
