from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.team_properties import TeamProperties
from openapi_server import util

from openapi_server.models.team_properties import TeamProperties  # noqa: E501

class TeamsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, team_selection_message=None, red=None, green=None):  # noqa: E501
        """TeamsResponse - a model defined in OpenAPI

        :param team_selection_message: The team_selection_message of this TeamsResponse.  # noqa: E501
        :type team_selection_message: str
        :param red: The red of this TeamsResponse.  # noqa: E501
        :type red: TeamProperties
        :param green: The green of this TeamsResponse.  # noqa: E501
        :type green: TeamProperties
        """
        self.openapi_types = {
            'team_selection_message': str,
            'red': TeamProperties,
            'green': TeamProperties
        }

        self.attribute_map = {
            'team_selection_message': 'teamSelectionMessage',
            'red': 'Red',
            'green': 'Green'
        }

        self._team_selection_message = team_selection_message
        self._red = red
        self._green = green

    @classmethod
    def from_dict(cls, dikt) -> 'TeamsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TeamsResponse of this TeamsResponse.  # noqa: E501
        :rtype: TeamsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def team_selection_message(self) -> str:
        """Gets the team_selection_message of this TeamsResponse.

        チームを選ぶ際に表示される全体へのメッセージ。  # noqa: E501

        :return: The team_selection_message of this TeamsResponse.
        :rtype: str
        """
        return self._team_selection_message

    @team_selection_message.setter
    def team_selection_message(self, team_selection_message: str):
        """Sets the team_selection_message of this TeamsResponse.

        チームを選ぶ際に表示される全体へのメッセージ。  # noqa: E501

        :param team_selection_message: The team_selection_message of this TeamsResponse.
        :type team_selection_message: str
        """

        self._team_selection_message = team_selection_message

    @property
    def red(self) -> TeamProperties:
        """Gets the red of this TeamsResponse.


        :return: The red of this TeamsResponse.
        :rtype: TeamProperties
        """
        return self._red

    @red.setter
    def red(self, red: TeamProperties):
        """Sets the red of this TeamsResponse.


        :param red: The red of this TeamsResponse.
        :type red: TeamProperties
        """

        self._red = red

    @property
    def green(self) -> TeamProperties:
        """Gets the green of this TeamsResponse.


        :return: The green of this TeamsResponse.
        :rtype: TeamProperties
        """
        return self._green

    @green.setter
    def green(self, green: TeamProperties):
        """Sets the green of this TeamsResponse.


        :param green: The green of this TeamsResponse.
        :type green: TeamProperties
        """

        self._green = green
